name: "Update Cachix"

on:
  pull_request:
  push:
  workflow_dispatch

jobs:
  update-cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sfdx-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
    - run: nix shell --command sh -c "echo OK"
